project:
  type: website
  resources:
    - "images/twitter-card.png"
    - "materials/*.pdf"
    - "slides.zip"
    - "labs.zip"
  render:
    - "*.qmd"
    - "!materials"
    - "!README.Rmd"
  pre-render: zip.R

website:
  page-navigation: true
  title: "Tidy time series & forecasting in R"
  description: "Homepage for Department of Education time series workshop"
  site-url: "https://workshop.nectric.com.au/deptedu2024"
  
  repo-url: https://github.com/mitchelloharawild/workshop-dept-education-2024
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
    image: "/images/twitter-card.png"

  favicon: "/images/fable.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2024, Nectric Pty Ltd"
    background: "#426D98"

  navbar:
    background: "#426D98"
    pinned: true
    align: center
    right:
      - icon: download
        text: Downloads
        menu: 
          - text: Everything
            href: 'https://github.com/mitchelloharawild/workshop-tidyfc-2024/archive/refs/heads/main.zip'
          - text: Slides
            href: 'slides.zip'
          - text: Lab sessions
            href: 'labs.zip'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/workshop-tidyfc-2024
    left:
      - text: Sessions
        menu: 
          - text: Background
            href: sessions/day1/00_intro.qmd
          - text: Introduction to tsibbles
            href: sessions/day1/01_tsibble.qmd
          - text: Time series graphics
            href: sessions/day1/02_graphics.qmd
          - text: Transformations
            href: sessions/day1/03_transformations.qmd
          - text: Seasonality and trends
            href: sessions/day1/04_decomposition.qmd
          - text: Forecasting basics
            href: sessions/day1/05_forecasting.qmd
          - text: Accuracy evaluation
            href: sessions/day2/06_accuracy.qmd
            # Add bias and endogeneity
            # Add segue of 'improving accuracy' (capturing more patterns)
          - text: Exponential smoothing
            href: sessions/day2/07_ets.qmd
            # Keep as-is
          - text: ARIMA models
            href: sessions/day2/08_arima.qmd
            # Keep mostly as-is, more attention on stationarity / ACF / PACF
          - text: Dynamic regression
            href: sessions/day2/09_dynreg.qmd
            # Emphasise incorporation of policy changes
          - text: Multivariate modelling
            href: sessions/day2/10_multivariate.qmd
            # Mostly on multivariate modelling (VAR, VECM, VARIMA)
            # Relate VAR and VECM (cointegration, conversion)
            # Impulse response functions
            # Estimation and identification problems
            # Include some hierarchical ('teaser' at the end)
      - href: schedule.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"
    include-after-body: plausible.html
