---
title: "Tidy Time Series & Forecasting Using R"
subtitle: "Australian Department of Education"
author: "Mitchell O'Hara-Wild"
format:
  beamer:
    pdf-engine: pdflatex
    aspectratio: 169
    fontsize: "14pt,t"
    section-titles: false
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
    fig-width: 7.5
    fig-height: 3.5
    include-in-header: header.tex
    keep-tex: false
---

```{r}
#| label: setup
#| include: false
#| cache: false
source("setup.R")
```

## Instructors

\placefig{0.6}{1.4}{width=3.5cm}{Mitch}
\begin{textblock}{8.2}(5.6,1.4)
\begin{alertblock}{Mitchell O'Hara-Wild}
\href{https://mitchelloharawild.com}{\faIcon{home} mitchelloharawild.com}\\
\href{https://github.com/mitchoharawild}{\faIcon{github}  @mitchelloharawild}\\
\href{mailto:mitchell@nectric.com.au}{\faIcon{envelope}  mitchell@nectric.com.au}
\end{alertblock}
\end{textblock}

\placefig{0.6}{5.4}{width=3.5cm}{Danyang}
\begin{textblock}{8.2}(5.6,5.4)
\begin{alertblock}{Danyang Dai (Helper)}
\href{https://dai.netlify.app/}{\faIcon{home} dai.netlify.app}\\
\href{https://github.com/DanyangDai}{\faIcon{github}  @DanyangDai}
\end{alertblock}
\end{textblock}

## Assumptions

  * This is not an introduction to R. We assume you are broadly comfortable with R code, the RStudio environment and the tidyverse.
  * This is not a statistics course. We assume you are familiar with concepts such as the mean, standard deviation, quantiles, regression, normal distribution, likelihood, etc.
  * This is not a theory course. We are not going to derive anything. We will teach you time series and forecasting tools, when to use them, and how to use them most effectively.

## Key reference

\large

\begin{block}{}\bf
\hangafter=1\hangindent=.3cm
 {Hyndman, R.~J. \& Athanasopoulos, G. (2021) \emph{Forecasting: principles and practice}, 3rd ed.}
\end{block}\pause
\begin{alertblock}{}\Large
\centerline{\bf OTexts.org/fpp3/}
\end{alertblock}

\pause

  * Free and online
  * Data sets in associated R package
  * R code for examples

## Poll: How experienced are you in forecasting

  1. Guru: I wrote the software, teach forecasting, and do the conference circuit.
  2. Expert: It has been my full time job for more than a decade.
  3. Skilled: I have been doing it for years.
  1. Comfortable: I understand it and have done it.
  1. Learner: I am still learning.
  1. Beginner: I have heard of it and would like to learn more.
  1. Unknown: What is forecasting? Is that what the weather people do?

## Poll: How proficient are you in using R?

\fontsize{14}{15}\sf

  1. Guru: The R core team come to me for advice.
  1. Expert: I have written several packages on CRAN.
  1. Skilled: I use it regularly and it is an important part of my job.
  1. Comfortable: I use it often and am comfortable with the tool.
  1. User: I use it sometimes, but I am often searching around for the right function.
  1. Learner: I have used it a few times.
  1. Beginner: I've managed to download and install it.
  1. Unknown: Why are you speaking like a pirate?

## Install required packages

```r
install.packages(c(
  "tidyverse",
  "fpp3",
  "readabs",
  "GGally",
  "sugrrants"
))
```

## Approximate outline
\vspace*{-0.1cm}\centering\fontsize{12}{12}\sf
\begin{tabular}{rp{6.6cm}l}
  \bf Day & \bf Topic                   & \bf fpp3 chapter \\
  \midrule
  1       & 1. Introduction to tsibbles    & 2 \\
  1       & 2. Time series graphics        & 2 \\
  1       & 3. Transformations             & 3 \\
  1       & 4. Decomposing patterns        & 3 \\
  1       & 5. Forecasting basics          & 5,7 \\
  \midrule
  2       & 6. Accuracy evaluation         & 5 \\
  2       & 7. Exponential smoothing       & 8 \\
  2       & 8. ARIMA models                & 9,10 \\
  2       & 9. Multivariate modelling      & 12 \\
  2       & 10. Forecast reconciliation    & 11 \\
  \bottomrule
\end{tabular}

\vspace*{.0cm}\begin{alertblock}{}{\centerline{\Large\textbf{workshop.nectric.com.au/tidyfc2024}}}
\end{alertblock}
